version: "3.7"

services:
  mariadb:
    image: mariadb:10.8
    restart: always
    environment:
      - ${MARIADB_ENV_KEY}=${MARIADB_ENV_VALUE}
    volumes:
      - ${MARIADB_VOLUMES_PATH}
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --port ${REDIS_PORT}
    container_name: m2m_redis
    hostname: m2m_redis
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPUS}"
          memory: ${REDIS_MEMORY}
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  m2m_service_traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    restart: always
    command:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
        #- "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.ws.address=:8081"
      - "--entryPoints.wss.address=:8083"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL_ADDRESS}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
      - "8083:8083"
    volumes:
      - "${TRAEFIK_LETSSENCRYPT_VOLUEMES}:/letsencrypt"
      - "${DOCKER_SOCK}:/var/run/docker.sock:ro"

  m2m_service_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "m2m_service_api"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.m2m_service_api.rule=Host(`${API_SERVER_BASE_URL}`)"
      - "traefik.http.routers.m2m_service_api.entrypoints=websecure"
      - "traefik.http.routers.m2m_service_api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https, wss"
      #https
      - "traefik.http.routers.m2m_service_api.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.m2m_service_api.entrypoints=web"
      - "traefik.http.routers.m2m_service_api.middlewares=redirect-to-https"
      # ws
      - "traefik.ws.routers.m2m_service_api.rule=Host(`${API_SERVER_BASE_URL}`)"
      - "traefik.ws.routers.m2m_service_api.entrypoints=ws"
      # wss
      - "traefik.wss.protocol=ws"
      - "traefik.wss.routers.m2m_service_api.rule=Host(`${API_SERVER_BASE_URL}`)"
      - "traefik.wss.routers.m2m_service_api.entrypoints=wss"
      - "traefik.wss.routers.m2m_service_api.tls=true"
      - "traefik.wss.routers.m2m_service_api.tls.certresolver=myresolver"
