version: "3.7"

services:
  mariadb:
    image: mariadb:10.8
    restart: always
    environment:
      - ${MARIADB_ENV_KEY}=${MARIADB_ENV_VALUE}
    volumes:
      - ${MARIADB_VOLUMES_PATH}
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --port ${REDIS_PORT}
    container_name: m2m_redis
    hostname: m2m_redis
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPUS}"
          memory: ${REDIS_MEMORY}
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    restart: always
    command:
      # - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      # - "--entrypoints.https.address.tls=true"
      - "--entryPoints.websocket.address=:8081"
      - "--entryPoints.websocketsecure.address=:8083"
      # - "--entrypoints.websocketsecure.address.tls=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL_ADDRESS}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--log.level=DEBUG"
      # - "--log.filePath=/path/to/log-file.log"
      # - "--log.format=json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
      - "8083:8083"
    volumes:
      - "${TRAEFIK_LETSSENCRYPT_VOLUEMES}:/letsencrypt"
      - "${DOCKER_SOCK}:/var/run/docker.sock:ro"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_SERVER_BASE_URL}`)"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      #https
      - "traefik.http.routers.api.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.middlewares=redirect-to-https"
      # ws
      - "traefik.http.routers.websocket.tls.certresolver=myresolver"
      - "traefik.http.routers.websocket.rule=Host(`${API_SERVER_BASE_URL}`)"
      - "traefik.http.routers.websocket.entrypoints=websocket"
      - "traefik.http.services.websocket.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.redirect-to-websocketsecure.redirectscheme.scheme=websocketsecure"
      # # wss
      - "traefik.http.routers.websocketsecure.rule=Host(`${API_SERVER_BASE_URL}`)"
      - "traefik.http.routers.websocketsecure.entrypoints=websocketsecure"
      - "traefik.http.routers.websocketsecure.tls=true"
      - "traefik.http.routers.websocketsecure.tls.certresolver=myresolver"
      - "traefik.http.services.websocketsecure.loadbalancer.server.port=8081"
