version: "3.7"

services:
  mariadb:
    image: mariadb:10.8
    restart: always
    environment:
      - ${MARIADB_ENV_KEY}=${MARIADB_ENV_VALUE}
    volumes:
      - ${MARIADB_VOLUMES_PATH}
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    networks:
      m2m_network:
        ipv4_address: 172.19.0.4

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --port ${REDIS_PORT}
    container_name: m2m_redis
    hostname: m2m_redis
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPUS}"
          memory: ${REDIS_MEMORY}
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      m2m_network:
        ipv4_address: 172.19.0.3

  nginx:
    image: "nginx:1.22"
    container_name: "nginx"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx_config/nginx_params:/etc/nginx/nginx_params
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      m2m_network:
        ipv4_address: 172.19.0.1

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  api:
    links:
      - mariadb:mariadb
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      m2m_network:
        ipv4_address: 172.19.0.2
    container_name: "api"
    restart: always

networks:
  m2m_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
