version: "3.7"

services:
  api:
    links:
      - mariadb:mariadb
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      m2m_network:
        ipv4_address: ${API_STATIC_IP}
    container_name: "api"
    volumes:
      - ./../../mnt/hdd1/m2m_public:/app/public
      - ./../../error_logs:/root/.npm/_logs/
    restart: always

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --port ${REDIS_PORT}
    container_name: m2m_redis
    hostname: m2m_redis
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPUS}"
          memory: ${REDIS_MEMORY}
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      m2m_network:
        ipv4_address: ${REDIS_STATIC_IP}

  mariadb:
    image: mariadb:10.8
    restart: always
    environment:
      - ${MARIADB_ENV_KEY}=${MARIADB_ENV_VALUE}
    volumes:
      - ${MARIADB_VOLUMES_PATH}
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    networks:
      m2m_network:
        ipv4_address: ${MARIADB_STATIC_IP}

networks:
  m2m_network:
    external:
      name: m2m_service
